LankaBookin/Controllers/UserRoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LankaBookin.Models;
using LankaBookin.DAL;

namespace LankaBookin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class UserRoleController : Controller
    {
        private LankaBookinEntities db = new LankaBookinEntities();

        //
        // GET: /UserRole/

        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }

        //
        // GET: /UserRole/Details/5

        public ActionResult Details(int id = 0)
        {
            Role webpages_roles = db.Roles.Find(id);
            if (webpages_roles == null)
            {
                return HttpNotFound();
            }

            ViewBag.Users = (from ur in db.UsersInRoles
                             join role in db.Roles on ur.RoleId equals role.RoleId
                             join user in db.User on ur.UserId equals user.Id
                             where role.RoleId == id
                             select user).ToList();

            return View(webpages_roles);
        }

        //
        // GET: /UserRole/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserRole/Create

        [HttpPost]
        public ActionResult Create(Role webpages_roles)
        {
            if (string.IsNullOrEmpty(webpages_roles.RoleName))
            {
                ModelState.AddModelError("", "Please enter role name");
            }

            if (ModelState.IsValid)
            {
                db.Roles.Add(webpages_roles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(webpages_roles);
        }

        //
        // GET: /UserRole/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Edit(int id = 0)
        {
            Role webpages_roles = db.Roles.Find(id);
            if (webpages_roles == null)
            {
                return HttpNotFound();
            }
            return View(webpages_roles);
        }

        //
        // POST: /UserRole/Edit/5

        [HttpPost]
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Edit(Role webpages_roles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(webpages_roles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(webpages_roles);
        }

        //
        // GET: /UserRole/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Delete(int id = 0)
        {
            Role webpages_roles = db.Roles.Find(id);
            if (webpages_roles == null)
            {
                return HttpNotFound();
            }
            return View(webpages_roles);
        }

        //
        // POST: /UserRole/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Role webpages_roles = db.Roles.Find(id);
            db.Roles.Remove(webpages_roles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LankaBookin/Views/UserRole/Create.cshtml
@model LankaBookin.Models.Role

@{
    ViewBag.Title = "User Role Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>


        <div class="editor-label">
            @Html.LabelFor(model => model.RoleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleName)
            @Html.ValidationMessageFor(model => model.RoleName)
        </div>

        <div class="col-md-2">
            <input type="submit" id="submit" value="Create" />
        </div>
        <div class="col-md-2 btn btn-info b-t-l">
            @Html.ActionLink("Back to List", "Index")
        </div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/UserRole/Delete.cshtml
@model LankaBookin.Models.Role

@{
    ViewBag.Title = "Delete User Role";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<p>&nbsp;</p>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RoleName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RoleName)
    </div>


@using (Html.BeginForm()) {
    <div class="col-md-2">
        <input type="submit" value="Delete" />
    </div>
    <div class="col-md-2 btn btn-info b-t-l">
        @Html.ActionLink("Back to List", "Index")
    </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
}

LankaBookin/Views/UserRole/Details.cshtml
@model LankaBookin.Models.Role

@{
    ViewBag.Title = "User Role Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<fieldset>


    <div class="display-label">
        @Html.DisplayNameFor(model => model.RoleName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RoleName)
    </div>

    <div class="display-label">
        @Html.Label("Users")
    </div>

    @foreach (var user in ViewBag.Users)
    {
        <div class="display-field">
            @Html.ActionLink((string)user.UserName, "Details", "User", new { id = user.Id }, null)
        </div>
    }

</fieldset>
<p>
    @if (User.IsInRole("SuperAdmin"))
    {
        <div class="col-md-2 btn btn-primary link-c-n">
            @Html.ActionLink("Edit", "Edit", new { id = Model.RoleId })
        </div>
    }

    <div class="col-md-2 btn btn-info">@Html.ActionLink("Back to List", "Index")</div>
</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

LankaBookin/Views/UserRole/Edit.cshtml
@model LankaBookin.Models.Role

@{
    ViewBag.Title = "Edit User Role";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>


        @Html.HiddenFor(model => model.RoleId)

        <div class="editor-label">
            @Html.LabelFor(model => model.RoleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleName)
            @Html.ValidationMessageFor(model => model.RoleName)
        </div>

        <div class="col-md-2">
            <input type="submit" value="Save" />
        </div>
        <div class="col-md-2 btn btn-info b-t-l">
            @Html.ActionLink("Back to List", "Index")
        </div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/UserRole/Index.cshtml
@model IEnumerable<LankaBookin.Models.Role>
@using GridMvc.Html

@{
    ViewBag.Title = "User Role List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>@ViewBag.Title</h2>

<div class="clear-fix">&nbsp;</div>
<div class="btn btn-danger link-c-n">
    @Html.ActionLink("Create New", "Create")
</div>

@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.RoleName).Titled("Role Name").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "UserRole", new { id = o.RoleId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());
              columns.Add().Titled("Actions").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Edit", "Edit", "UserRole", new { id = o.RoleId, page = ViewBag.Page }, new { @class = "btn btn-success" }).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Delete", "Delete", "UserRole", new { id = o.RoleId, page = ViewBag.Page }, new { @class = "btn btn-danger modal-link" }).ToHtmlString());

          }).WithPaging(10)