LankaBookin/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LankaBookin.Models
{
    [Table("Lb_Apartment")]
    public class Apartment:BaseModel
    {
        public Apartment()
        {
            this.RoomsBook = new HashSet<RoomsBook>();
            this.Rating = new HashSet<Rating>();
            this.Reviews = new HashSet<Review>();
            this.UserWishList = new HashSet<UserWishList>();
            this.BookingRequest = new HashSet<BookingRequest>();
            this.Facilities = new HashSet<Facility>();
            this.Accomadations = new HashSet<AccomadationType>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Ref No")]
        public string RefNo { get; set; }

        [Required]
        [Display(Name = "Property Name")]
        [MaxLength(100, ErrorMessage = "Name exceeds the maximum length")]
        public string Name { get; set; }

        public decimal Rate { get; set; }

        [Required]
        [Display(Name = "Address Line 1")]
        [MaxLength(200, ErrorMessage = "Address exceeds the maximum length")]
        public string Address { get; set; }

        [Display(Name = "Address Line 2")]
        [MaxLength(200, ErrorMessage = "Address exceeds the maximum length")]
        public string Address2 { get; set; }

        [Required]
        [Display(Name = "Description")]
        [MaxLength(10000, ErrorMessage = "Description exceeds the maximum length")]
        public string Description { get; set; }

        [Display(Name = "Remarks")]
        public string Remarks { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "MetaDescription")]
        public string MetaDescription { get; set; }

        [Display(Name = "Per room basis")]
        public bool IsPerRoom { get; set; }

        [Display(Name = "Per room per night")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<decimal> PricePerRoom { get; set; }

        [Display(Name = "Whole property per night")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<decimal> WholePricePerDay { get; set; }

        [Display(Name = "Whole property per week")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<decimal> WholePricePerWeek { get; set; }

        [Display(Name = "Whole property per month")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<decimal> WholePricePerMonth { get; set; }

        [Display(Name = "Sleeps")]
        public int MaxHeadCount { get; set; }

        [Display(Name = "Bedrooms")]
        public int NoOfBedrooms { get; set; }

        [Display(Name = "Bathrooms")]
        public int NoOfBathrooms { get; set; }

        [Required]
        [Display(Name = "User Name")]
        public int UserId { get; set; }

        [Required]
        [Display(Name = "City Name")]
        public int CityId { get; set; }

        [Display(Name = "Lankmark Name")]
        public Nullable<int> LandmarkId { get; set; }

        public string Lat { get; set; }

        public string Lan { get; set; }

        public string MainImagePath { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual Landmark Landmark { get; set; }
        public virtual ICollection<RoomsBook> RoomsBook { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual ICollection<UserWishList> UserWishList { get; set; }
        public virtual ICollection<BookingRequest> BookingRequest { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<AccomadationType> Accomadations { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}

LankaBookin/Controllers/ApartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LankaBookin.Models;
using LankaBookin.DAL;
using WebMatrix.WebData;
using System.IO;
using PagedList;
using LankaBookin.Common;
using Newtonsoft.Json;
using GoogleMaps.LocationServices;
using System.Net.Http;
using LankaBookin.CurrencyConverter;
using ImageResizer;

namespace LankaBookin.Controllers
{
    public class ApartmentController : Controller
    {
        private LankaBookinEntities db = new LankaBookinEntities();

        //
        // GET: /Apartment/
        [Authorize]
        [Authorize(Roles = "Internal")]
        public ActionResult Index()
        {
            int userId = WebSecurity.GetUserId(User.Identity.Name);
            return View(db.Apartment.Where(a => a.UserId == userId && a.Deleted != true).ToList());
        }

        [Authorize]
        public ActionResult ApartmentList(DateTime? checkin = null, DateTime? checkout = null,int desId=0)
        {
            ViewBag.DesId = desId;
            return PartialView(db.Apartment.Where(a => a.Deleted != true).ToList());
        }

        public ActionResult CancelTour()
        {
            if (HttpContext.Request.Cookies["TourRequest"] != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("TourRequest");
                cookie.Expires = DateTime.Now.AddDays(-1);
                HttpContext.Response.SetCookie(cookie);
            }

            return RedirectToAction("Index","Home");
        }

        //
        // GET: /Apartment/
        [AllowAnonymous]
        [OutputCache(Duration = int.MaxValue, VaryByParam = "search;checkin;checkout;no_rooms;search_prop_type;page;cityId;districtId;minPrice;maxPrice;tourId")]
        public ActionResult Search(string search = "", DateTime? checkin = null, DateTime? checkout = null, int no_rooms = 0, int search_prop_type = 0, int? page = 0, int cityId = 0, int districtId = 0, int minPrice = 0, int maxPrice = 0,int tourId=0)
        {
            if (tourId != 0 && HttpContext.Request.Cookies["TourRequest"] != null)
            {
                var tourDestination = db.TourDestination.Find(tourId);
                if (tourDestination != null)
                {
                    ViewBag.CityName = tourDestination.City.CityName;
                    ViewBag.TourName = tourDestination.Tour.TourName;
                    ViewBag.tourId = tourId;

                    HttpCookie cookie = HttpContext.Request.Cookies.Get("TourRequest");
                    cookie["stepId"] = tourId.ToString();
                    HttpContext.Response.Cookies.Remove("TourRequest");
                    HttpContext.Response.SetCookie(cookie);
                }
            }
            else if (HttpContext.Request.Cookies["TourRequest"] != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("TourRequest");
                var tourid = cookie["stepId"];
                if (!string.IsNullOrEmpty(tourid))
                {
                    tourId = Convert.ToInt32(tourid);
                    var tourDestination = db.TourDestination.Find(tourId);
                    if (tourDestination != null)
                    {
                        ViewBag.CityName = tourDestination.City.CityName;
                        ViewBag.TourName = tourDestination.Tour.TourName;
                        ViewBag.tourId = tourId;
                    }
                }
            }

            List<Facility> facilityList = new List<Facility>();

            List<Facility> facilityFullList = db.Facility.Where(f=>f.Priority!=3).ToList();
            foreach (Facility type in facilityFullList)
            {
                var result = Request[Convert.ToString("Fac" + type.Id)];
                if (result != null)
                {
                    if (result.ToString() == "on")
                    {
                        facilityList.Add(type);
                    }
                }

            }

            if (page == 0)
            {
                Session.Remove("values");

                Dictionary<string, object> dic = new Dictionary<string, object>();
                dic.Add("min", minPrice);
                dic.Add("max", maxPrice);
                dic.Add("facilityList", facilityList);
                dic.Add("search", search);
                dic.Add("checkin", checkin);
                dic.Add("checkout", checkout);
                dic.Add("search_prop_type", search_prop_type);
                dic.Add("no_rooms", no_rooms);
                dic.Add("districtId", districtId);
                dic.Add("cityId", cityId);
                Session.Add("values", dic);
            }
            else
            {
                var dic = Session["values"];
                if (dic != null)
                {
                    Dictionary<string, object> values = (Dictionary<string, object>)dic;

                    if (values["min"]!=null)
                    {
                        if (!string.IsNullOrEmpty(values["min"].ToString()))
                        {
                            minPrice = Convert.ToInt32(values["min"]);
                        }
                    }

                    if (values["max"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["max"].ToString()))
                        {
                            maxPrice = Convert.ToInt32(values["max"]);
                        }
                    }

                    if (values["facilityList"]!=null)
                    {
                        facilityList = (List<Facility>)values["facilityList"];
                    }

                    if (values["search"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["search"].ToString()))
                        {
                            search = Convert.ToString(values["search"]);
                        }
                    }

                    if (values["checkin"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["checkin"].ToString()))
                        {
                            checkin = Convert.ToDateTime(values["checkin"]);
                        }
                    }

                    if (values["checkout"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["checkout"].ToString()))
                        {
                            checkout = Convert.ToDateTime(values["checkout"]);
                        }
                    }

                    if (values["search_prop_type"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["search_prop_type"].ToString()))
                        {
                            search_prop_type = Convert.ToInt32(values["search_prop_type"]);
                        }
                    }

                    if (values["no_rooms"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["no_rooms"].ToString()))
                        {
                            no_rooms = Convert.ToInt32(values["no_rooms"]);
                        }
                    }

                    if (values["districtId"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["districtId"].ToString()))
                        {
                            districtId = Convert.ToInt32(values["districtId"]);
                        }
                    }

                    if (values["cityId"] != null)
                    {
                        if (!string.IsNullOrEmpty(values["cityId"].ToString()))
                        {
                            cityId = Convert.ToInt32(values["cityId"]);
                        }
                    }
                }
            }

            List<Apartment> apartments;
            List<Apartment> apartmentList;

            if (!string.IsNullOrEmpty(search) && !search.Contains("Search By Name"))
            {
                apartments = db.Apartment.Where(a => a.Deleted != true && a.Name.Contains(search)).OrderByDescending(a=>a.Rate).ToList();
                apartmentList = db.Apartment.Where(a => a.Deleted != true && a.Name.Contains(search)).OrderByDescending(a => a.Rate).ToList();
            }
            else
            {
                apartments = db.Apartment.Where(a => a.Deleted != true).OrderByDescending(a => a.Rate).ToList();
                apartmentList = db.Apartment.Where(a => a.Deleted != true).OrderByDescending(a => a.Rate).ToList();
            }

            var cities = db.District.Where(d => d.Id == districtId).Select(d => d.City.Select(c=>c.Id)).FirstOrDefault();

            foreach (var apartment in apartments)
            {
                if (checkin != null && checkout != null)
                {
                    DateTime date=(DateTime)checkin;
                    while(date<=checkout)
                    {
                        var result = db.RoomsBook.Where(r => r.ApartmentId == apartment.Id && r.Date == date).Select(r=>r.booked);
                        if (result != null)
                        {
                            apartmentList.Remove(apartment);
                        }

                        date = date.AddDays(1);
                    }

                }

                if (maxPrice > minPrice)
                {
                    if (apartment.IsPerRoom)
                    {
                        if (apartment.PricePerRoom < minPrice || apartment.PricePerRoom > maxPrice)
                        {
                            apartmentList.Remove(apartment);
                        }
                    }
                    else
                    {
                        if (apartment.WholePricePerDay < minPrice || apartment.WholePricePerDay > maxPrice)

LankaBookin/Views/Apartment/ApartmentList.cshtml
@model IEnumerable<LankaBookin.Models.Apartment>
@using GridMvc.Html
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Styles.Render("~/Content/themes/base/css")

<style>
    .popup {
        width: 900px !important;
        margin: 30px auto !important;
    }
</style>

@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.Name).Titled("Apartment Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Rate).Titled("Rating").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Description).Titled("Description").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "DetailsPartial", "Apartment", new { id = o.Id, page = ViewBag.Page }, new { @class = "popup" }).ToHtmlString());
              columns.Add().Encoded(false).Sanitized(false).RenderValueAs(o => @<label class="selectAprt" id="saprt@(o.Id)">Select apartment</label>);

          }).WithPaging(10)


<div id="divInDialog">

</div>

        <script type="text/javascript">

            $(document).ready(function () {

                $('.popup').click(function () {
                    $('#divInDialog').dialog({
                        close: function (event, ui) {
                            dialog.remove();
                        },
                        modal: true
                    }).load(this.href, {});

                    return false;
                });

                $('.selectAprt').click(function (e) {
                    var desId = '@ViewBag.DesId';
                    var ids = e.target.id;
                    var id = ids.substring(5);
                    $('#sa' + desId).val(id);
                    $.getJSON("/Apartment/GetApartmentName", { apartmentId: id },
                  function (data, status) {
                      $('#aprt_name' + desId).val(data.name);
                      if (data.isPerRoom) {
                          $('#price_des' + desId).text('Price per room');
                      }
                      else {
                          $('#price_des' + desId).text('Price per whole apartment');
                      }
                      $('#price' + desId).val(data.price);
                      $('#d' + desId).show();
                      $('#window').hide();
                  });

                });

            });
        </script>

LankaBookin/Views/Apartment/Create.cshtml
@model LankaBookin.Models.Apartment

@{
    ViewBag.Title = "Apartment Create";
    Layout = "~/Views/Shared/_UserProfileLayout.cshtml";
}

<h2>Create</h2>

<div class="submit-progress hidden">

    <label>Please wait while Saving Data...</label>

</div>


@using (Html.BeginForm("Create", "Apartment", FormMethod.Post,
                            new { enctype = "multipart/form-data", id = "Form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>New Property</legend>

        @Html.Hidden("RefNo", (String)ViewBag.RefNo)
        @Html.Hidden("Lat", "")
        @Html.Hidden("Lan", "")
        <div class="col-md-12">
            <div class="editor-label">
                @Html.LabelFor(model => model.RefNo) :  @Html.Label((String)ViewBag.RefNo)
            </div>
        </div>
        <div class="col-md-12">
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", new { id = "nameVal" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="editor-label">
                @Html.LabelFor(model => model.Address)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>
        <div class="col-md-6">
            <div class="editor-label">
                @Html.LabelFor(model => model.Address2)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address2)
                @Html.ValidationMessageFor(model => model.Address2)
            </div>
        </div>
        <div class="col-md-12">
            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        <div class="col-md-12">
            <div>
                <label>Select Accomadation Type </label>
                @foreach (var item in ViewBag.AccomadationTypes)
                {
                    <input type="checkbox" id="Acc@(item.Id)" name="Acc@(item.Id)" />
                    @item.AccomadationName 
                }

            </div>
        </div>
        <div class="col-md-12">

            <div class="editor-field">
                @Html.LabelFor(model => model.IsPerRoom)
                @Html.EditorFor(model => model.IsPerRoom)
                @Html.ValidationMessageFor(model => model.IsPerRoom)
            </div>
        </div>
        <div class="col-md-12">

            <div class="editor-field">
                @Html.Label("Whole villa basis")
                <input type="checkbox" id="wholecheck" />
            </div>
        </div>
        <div id="Whole">
            <div class="col-md-4">
                <div class="editor-label">
                    @Html.LabelFor(model => model.WholePricePerDay)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.WholePricePerDay)
                    @Html.ValidationMessageFor(model => model.WholePricePerDay)
                </div>
            </div>
            <div class="col-md-4">
                <div class="editor-label">
                    @Html.LabelFor(model => model.WholePricePerWeek)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.WholePricePerWeek)
                    @Html.ValidationMessageFor(model => model.WholePricePerWeek)
                </div>
            </div>
            <div class="col-md-4">
                <div class="editor-label">
                    @Html.LabelFor(model => model.WholePricePerMonth)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.WholePricePerMonth)
                    @Html.ValidationMessageFor(model => model.WholePricePerMonth)
                </div>
            </div>
            <div class="col-md-4">
                <div class="editor-label">
                    @Html.LabelFor(model => model.MaxHeadCount)
                </div>
                <div class="editor-field">
                    @Html.DropDownList("MaxHeadCount", (SelectList)ViewBag.MaxHeadCount, htmlAttributes: new { @class = "col-sm-12" })
                    @Html.ValidationMessageFor(model => model.MaxHeadCount)
                </div>
            </div>
            <div class="col-md-4">
                <div class="editor-label">
                    @Html.LabelFor(model => model.NoOfBedrooms)
                </div>
                <div class="editor-field">
                    @Html.DropDownList("NoOfBedrooms", (SelectList)ViewBag.NoOfBedrooms, htmlAttributes: new { @class = "col-sm-12" })
                    @Html.ValidationMessageFor(model => model.NoOfBedrooms)
                </div>
            </div>
            <div class="col-md-4">
                <div class="editor-label">
                    @Html.LabelFor(model => model.NoOfBathrooms)
                </div>
                <div class="editor-field">
                    @Html.DropDownList("NoOfBathrooms", (SelectList)ViewBag.NoOfBathrooms, htmlAttributes: new { @class = "col-sm-12" })
                    @Html.ValidationMessageFor(model => model.NoOfBathrooms)
                </div>
            </div>
        </div>

        <div id="room">
            <div class="editor-label">
                @Html.LabelFor(model => model.PricePerRoom)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PricePerRoom)
                @Html.ValidationMessageFor(model => model.PricePerRoom)
            </div>

        </div>
        <div class="col-md-12">
            <div class="editor-label">
                @Html.Label("Select a District")
            </div>
            <div class="editor-field">
                @Html.DropDownList("DistrictId", (SelectList)ViewBag.DistrictId, String.Empty, new { @onchange = "javascript:GetCity(this.value);" })
            </div>
        </div>
        <div class="col-md-12">
            <div class="editor-label">
                @Html.LabelFor(model => model.CityId, "City")
            </div>
            <div class="editor-field">
                @Html.DropDownList("CityId", String.Empty)
                @Html.ValidationMessageFor(model => model.CityId)
            </div>
        </div>
        <div class="col-md-6">
            @{int catId = 0;}
            @foreach (LankaBookin.Models.Facility item in ViewBag.Facilities)
            {
                if (catId != item.FacilityCategoryId)
                {
                    catId = item.FacilityCategoryId;
                <div class="col-md-12">
                    <h4>@item.FacilityCategory.FacilityCategoryName</h4>
                    <br />
                </div>
                }

                <div class="col-md-6">
                    <input type="checkbox" id="Fac@(item.Id)" name="Fac@(item.Id)" />
                    @item.FacilityName
                    <br />
                </div>

            }

        </div>

        <div class="col-md-6">
            <label>Set the Location</label>
            <div id="dvMap" style="width: 100%; height: 500px">
            </div>
        </div>

        @*<label for="file">Upload Profile Image</label>
        <input type="file" name="file" id="file" style="width:100px" />
        @Html.ValidationMessage("uploadMain")

        <div style="clear:both"></div>

        <img id="mainImage" src="#" alt="your image" style="width: 100px;height:100px"/>

        <div style="clear:both"></div>

        <label for="file">Click to Add Images:(Maxmimum 15 images)</label>

        <input type="file" id="uploadEditorImage" />

        <div style="clear:both"></div>

        <div id="divImage">
        </div>
        @Html.ValidationMessage("upload")

        <div style="clear:both"></div>*@
        <div class="col-md-12">
        <div class="col-md-2" >
            <input id="save" type="submit" value="Create" />
        </div>
            <div class="col-md-2 btn btn-info" style="margin-top:18px;">
    @Html.ActionLink("Back to List", "Index")
</div>
            </div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

<script>

    //$('form').submit(function () {
    //    $('#save').attr('disabled', 'disabled');
    //});

    var map;

    var marker;

    window.onload = function () {
        geocoder = new google.maps.Geocoder();
        var mapOptions = {
            center: new google.maps.LatLng(6.6, 80.3),
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var infoWindow = new google.maps.InfoWindow();
        var latlngbounds = new google.maps.LatLngBounds();
        map = new google.maps.Map(document.getElementById("dvMap"), mapOptions);
    }

    function codeAddress() {

        if (marker != null) {
            marker.setMap(null);
        }

        var address1 = document.getElementById("Address").value;
        var address2 = document.getElementById("Address2").value;
        var address = address1 + ' ' + address2;
        geocoder.geocode({ 'address': address }, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);
                marker = new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    draggable: true,
                });

                document.getElementById('Lat').value = marker.getPosition().lat();
                document.getElementById('Lan').value = marker.getPosition().lng();
            }

            google.maps.event.addListener(marker, 'dragend', function (event) {
                document.getElementById('Lat').value = marker.getPosition().lat();
                document.getElementById('Lan').value = marker.getPosition().lng();
            });
        });
    }

    $(document).ready(function () {

        var namevalid = true;

        $('#Name').on('input propertychange paste', CheckValidApartmentName);

        function CheckValidApartmentName() {
            $.getJSON("/Apartment/CheckValidApartmentName", { name: $("#Name").val() },
              function (data, status) {
                  if (!data.valid) {
                      $('#nameVal').text('Apartment name is already in use');
                      namevalid = false;
                  }
                  else {
                      $('#nameVal').text('');
                      namevalid = true;
                  }
              }
          );
        }

        $("#Form").submit(function (e) {
            if ($(this).valid() && namevalid) {
                $('#save').attr('disabled', 'disabled');
                $(".submit-progress").removeClass("hidden");
                $("body").addClass("submit-progress-bg");
            }
            else {
                e.preventDefault();
                $('#save').removeAttr("disabled");
            }
        });

        $('#Whole').fadeIn('slow');
        $('#room').fadeOut('slow');
        $('#wholecheck').prop('checked', true);
        $('#IsPerRoom').prop('checked', false);

        $('#IsPerRoom').change(function () {
            if (this.checked) {
                $('#Whole').fadeOut('slow');
                $('#room').fadeIn('slow');
                $('#wholecheck').prop('checked', false);
            }
            else {
                $('#Whole').fadeIn('slow');
                $('#room').fadeOut('slow');
                $('#wholecheck').prop('checked', true);
            }

        });

        $('#wholecheck').change(function () {
            if (this.checked) {
                $('#Whole').fadeIn('slow');
                $('#room').fadeOut('slow');
                $('#IsPerRoom').prop('checked', false);
            }
            else {
                $('#Whole').fadeOut('slow');
                $('#room').fadeIn('slow');
                $('#IsPerRoom').prop('checked', true);
            }

        });

        $('#Address').change(function () {
            codeAddress();
        });

        $('#Address2').change(function () {
            codeAddress();
        });

    });

    function GetCity(_districtid) {
        var procemessage = "<option value='0'> Please wait...</option>";
        $("#CityId").html(procemessage).show();
        var url = "/Apartment/GetCityByDisId/";

        $.ajax({
            url: url,
            data: { districtid: _districtid },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select City</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                }
                $("#CityId").html(markup).show();
            },
            error: function (reponse) {
            }
        });

    }

</script>