LankaBookin/Controllers/AccomadationTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LankaBookin.Models;
using LankaBookin.DAL;
using WebMatrix.WebData;

namespace LankaBookin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class AccomadationTypeController : Controller
    {
        private LankaBookinEntities db = new LankaBookinEntities();

        //
        // GET: /AccomadationType/

        public ActionResult Index()
        {
            return View(db.AccomadationType.ToList());
        }

        //
        // GET: /AccomadationType/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AccomadationType/Create

        [HttpPost]
        public ActionResult Create(AccomadationType accomadationtype)
        {
            if (ModelState.IsValid)
            {
                int userId = WebSecurity.GetUserId(User.Identity.Name);
                accomadationtype.CreatedBy = userId;
                accomadationtype.CreatedDate = DateTime.Now;
                accomadationtype.Deleted = false;
                db.AccomadationType.Add(accomadationtype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accomadationtype);
        }

        //
        // GET: /AccomadationType/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AccomadationType lb_accomadationtype = db.AccomadationType.Find(id);
            if (lb_accomadationtype == null)
            {
                return HttpNotFound();
            }
            return View(lb_accomadationtype);
        }

        //
        // POST: /AccomadationType/Edit/5

        [HttpPost]
        public ActionResult Edit(AccomadationType accomadationtype)
        {
            if (ModelState.IsValid)
            {
                int userId = WebSecurity.GetUserId(User.Identity.Name);
                accomadationtype.ModifiedDate = DateTime.Now;
                accomadationtype.ModifiedBy = userId;
                db.Entry(accomadationtype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accomadationtype);
        }

        //
        // GET: /AccomadationType/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Delete(int id = 0)
        {
            AccomadationType lb_accomadationtype = db.AccomadationType.Find(id);
            if (lb_accomadationtype == null)
            {
                return HttpNotFound();
            }
            return View(lb_accomadationtype);
        }

        //
        // POST: /AccomadationType/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {
            AccomadationType accomadationtype = db.AccomadationType.Find(id);
            db.AccomadationType.Remove(accomadationtype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LankaBookin/Views/AccomadationType/Create.cshtml
@model LankaBookin.Models.AccomadationType

@{
    ViewBag.Title = "Create Accomadation Type";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>

        <div class="editor-label">
            @Html.LabelFor(model => model.AccomadationName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccomadationName)
            @Html.ValidationMessageFor(model => model.AccomadationName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="col-md-2">
            <input id="save" type="submit" value="Create" />
        </div>
        <div class="col-md-2 btn btn-info b-t-l">
    @Html.ActionLink("Back to List", "Index")
</div>
    </fieldset>
}

<p>&nbsp;</p>

<script>

    //$('form').submit(function () {
    //    $('#save').attr('disabled', 'disabled');
    //});

</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/AccomadationType/Delete.cshtml
@model LankaBookin.Models.AccomadationType

@{
    ViewBag.Title = "Delete Accomadation Type";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<p>&nbsp;</p>
<fieldset>

    @Html.HiddenFor(model => model.Id)

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AccomadationName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AccomadationName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
   
</fieldset>
@using (Html.BeginForm()) {
    <div class="col-md-2">
        <input type="submit" value="Delete" />
        </div>
    
        <div class="col-md-2 btn btn-info b-t-l">@Html.ActionLink("Back to List", "Index")</div>


}
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

LankaBookin/Views/AccomadationType/Edit.cshtml
@model LankaBookin.Models.AccomadationType

@{
    ViewBag.Title = "Edit Accomadation Type";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Deleted)
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.CreatedDate)

        <div class="editor-label">
            @Html.LabelFor(model => model.AccomadationName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccomadationName)
            @Html.ValidationMessageFor(model => model.AccomadationName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="col-md-2">
            <input type="submit" value="Save" />
        </div>
        <div class="col-md-2 btn btn-info b-t-l">
    @Html.ActionLink("Back to List", "Index")
</div>
    </fieldset>
    <p>&nbsp;</p>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/AccomadationType/Index.cshtml
@model IEnumerable<LankaBookin.Models.AccomadationType>
@using GridMvc.Html

@{
    ViewBag.Title = "Accomadation Type List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}

<h2>@ViewBag.Title</h2>
<div class="clear-fix">&nbsp;</div>
<div class="btn btn-danger link-c-n">
    @Html.ActionLink("Create New", "Create")
</div>

@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.AccomadationName).Titled("Accomadation Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Description).Titled("Description").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("Actions").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Edit", "Edit", "AccomadationType", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-success" }).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Delete", "Delete", "AccomadationType", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-danger modal-link" }).ToHtmlString());

          }).WithPaging(10)