LankaBookin/Controllers/AdminBookingRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LankaBookin.Models;
using LankaBookin.DAL;
using LankaBookin.Common;

namespace LankaBookin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class AdminBookingRequestController : Controller
    {
        private LankaBookinEntities db = new LankaBookinEntities();

        //
        // GET: /AdminBookingRequest/

        public ActionResult Index()
        {
            var bookingrequest = db.BookingRequest.Where(b => b.Deleted != true).ToList();
            return View(bookingrequest);
        }

        //
        // GET: /AdminBookingRequest/Details/5

        public ActionResult Details(int id = 0)
        {
            BookingRequest bookingrequest = db.BookingRequest.Find(id);
            if (bookingrequest == null)
            {
                return HttpNotFound();
            }
            return View(bookingrequest);
        }
       

        //
        // GET: /AdminBookingRequest/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    BookingRequest bookingrequest = db.BookingRequest.Find(id);
        //    if (bookingrequest == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ApartmentId = new SelectList(db.Apartment, "Id", "Name", bookingrequest.ApartmentId);
        //    ViewBag.UserId = new SelectList(db.User, "Id", "Name", bookingrequest.UserId);
        //    return View(bookingrequest);
        //}

        ////
        //// POST: /AdminBookingRequest/Edit/5

        //[HttpPost]
        //public ActionResult Edit(BookingRequest bookingrequest)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        int userId = Convert.ToInt32(Session[Common.SessionVariables.UserId.ToString()]);
        //        bookingrequest.ModifiedBy = userId;
        //        bookingrequest.ModifiedDate = DateTime.Now;
        //        db.Entry(bookingrequest).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ApartmentId = new SelectList(db.Apartment, "Id", "Name", bookingrequest.ApartmentId);
        //    ViewBag.UserId = new SelectList(db.User, "Id", "Name", bookingrequest.UserId);
        //    return View(bookingrequest);
        //}

        //
        // GET: /AdminBookingRequest/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Delete(int id = 0)
        {
            BookingRequest bookingrequest = db.BookingRequest.Find(id);
            if (bookingrequest == null)
            {
                return HttpNotFound();
            }
            return View(bookingrequest);
        }

        //
        // POST: /AdminBookingRequest/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            BookingRequest bookingrequest = db.BookingRequest.Find(id);
            bookingrequest.Deleted = true;
            db.Entry(bookingrequest).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult IsPerRoom(int apartmentId)
        {
            Apartment apartment = db.Apartment.Find(apartmentId);
            return Json(new { isPerRoom = apartment.IsPerRoom, price = apartment.PricePerRoom }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CalculatePrice(int apartmentId, int roomCount)
        {
            Apartment apartment = db.Apartment.Find(apartmentId);
            var price = apartment.PricePerRoom * roomCount;
            return Json(new { price = price }, JsonRequestBehavior.AllowGet);
        }
    }
}

LankaBookin/Views/AdminBookingRequest/Create.cshtml
@model LankaBookin.Models.BookingRequest

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BookingRequest</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApartmentId, "Apartment")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ApartmentId",string.Empty)
            @Html.ValidationMessageFor(model => model.ApartmentId)
        </div>

        <div id="Rooms">
            <div class="editor-label">
                @Html.LabelFor(model => model.RoomsBooked,"Number of Rooms")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.RoomsBooked,new { id  = "RoomsBook" })
                @Html.ValidationMessageFor(model => model.RoomsBooked)
            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price,"Amount")
        </div>
        <div class="editor-field">
             @Html.TextBoxFor(model => model.Price,new {id="price" })
             @Html.ValidationMessageFor(model => model.Price)
         </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CheckIn)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CheckIn,new {id="checkIn" })
            @Html.ValidationMessageFor(model => model.CheckIn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CheckOut)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CheckOut,new {id="checkOut" })
            @Html.ValidationMessageFor(model => model.CheckOut)
        </div>

        <div class="col-md-2">
            <input type="submit" value="Create" />
        </div>
        <div class="col-md-2 btn btn-info">
    @Html.ActionLink("Back to List", "Index")
</div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </fieldset>
}

      <script>
          $(function () {

              $("#ApartmentId").change(function () {
                  $.getJSON("/AdminBookingRequest/IsPerRoom", { apartmentId: $("#ApartmentId").val() },
                      function (data, status) {
                          if (!Boolean(data.isPerRoom)) {
                              $("#Rooms").hide();
                              $("#RoomsBook").val(0);
                              $("#price").val(data.price);
                          }
                          else {
                              $("#Rooms").show();
                              $("#price").val("");
                          }
                      }
                  );
              });

              $('#RoomsBook').on('input propertychange paste', function () {
                  $.getJSON("/AdminBookingRequest/CalculatePrice", { apartmentId: $("#ApartmentId").val(), roomCount: $("#RoomsBook").val() },
                    function (data, status) {
                        $("#price").val(data.price);
                    }
                );
              });

              $("#checkIn").datepicker();

              $("#checkOut").datepicker();

          });

        </script>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/AdminBookingRequest/Delete.cshtml
@model LankaBookin.Models.BookingRequest

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<p>&nbsp;</p>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Apartment.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Apartment.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OrderDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OrderDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CheckIn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CheckIn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CheckOut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CheckOut)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RoomsBooked)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RoomsBooked)
    </div>

@using (Html.BeginForm()) {
    <div class="col-md-2">
        <input type="submit" value="Delete" />
        </div>
        <div class="col-md-2 btn btn-info b-t-l">
            @Html.ActionLink("Back to List", "Index")
            </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
}

LankaBookin/Views/AdminBookingRequest/Details.cshtml
@model LankaBookin.Models.BookingRequest

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>BookingRequest</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Apartment.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Apartment.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OrderDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OrderDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CheckIn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CheckIn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CheckOut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CheckOut)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RoomsBooked)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RoomsBooked)
    </div>

</fieldset>
<p>
@*    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |*@
    <div class="btn btn-info">@Html.ActionLink("Back to List", "Index")</div>
</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

LankaBookin/Views/AdminBookingRequest/Edit.cshtml
@model LankaBookin.Models.BookingRequest

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BookingRequest</legend>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Deleted)

        <div class="editor-label">
            @Html.LabelFor(model => model.ApartmentId, "Apartment")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ApartmentId", String.Empty)
            @Html.ValidationMessageFor(model => model.ApartmentId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderDate)
            @Html.ValidationMessageFor(model => model.OrderDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CheckIn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CheckIn)
            @Html.ValidationMessageFor(model => model.CheckIn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CheckOut)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CheckOut)
            @Html.ValidationMessageFor(model => model.CheckOut)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RoomsBooked)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoomsBooked)
            @Html.ValidationMessageFor(model => model.RoomsBooked)
        </div>

        <div class="col-md-2">
            <input type="submit" value="Save" />
        </div>
        <div class="col-md-2 btn btn-info">
    @Html.ActionLink("Back to List", "Index")
</div>
        <p>&nbsp;</p
            <p>&nbsp;</p>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/AdminBookingRequest/Index.cshtml
@model IEnumerable<LankaBookin.Models.BookingRequest>
@using GridMvc.Html

@{
    ViewBag.Title = "Booking Requests";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.Apartment.Name).Titled("Apartment Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Price).Titled("Price").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.User.Name).Titled("User Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.OrderDate).Titled("OrderDate").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.CheckIn).Titled("CheckIn").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.CheckOut).Titled("CheckOut").SetWidth(120).Sortable(true).Filterable(true);


              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "AdminBookingRequest", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("Delete", "Delete", "AdminBookingRequest", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-danger modal-link" }).ToHtmlString());

          }).WithPaging(10)